### PR TITLE
Update parse-sdk.js to latest version

### PR DESCRIPTION
**Pull request by oddgoo**
Proposing latest (1.4.2, minified)

### CODE REVIEW

**Comment by jcastelli** [comment]
Thanks @oddgoo!

**Comment by oddgoo** [comment]
My pleasure!

On Wed, May 13, 2015 at 11:25 PM, Joe Castelli <notifications@github.com>
wrote:

> Thanks @oddgoo <https://github.com/oddgoo>!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jcastelli/meteor-parse-sdk/pull/3#issuecomment-101663033>
> .
>



-- 
*Cuauhtemoc Moreno*
*Creative Coder and Game Designer*

**Comment by oddgoo** [comment]
This was my first ever pull request haha

On Wed, May 13, 2015 at 11:41 PM, Cuauhtemoc Moreno <oddgoo@gmail.com>
wrote:

> My pleasure!
>
> On Wed, May 13, 2015 at 11:25 PM, Joe Castelli <notifications@github.com>
> wrote:
>
>> Thanks @oddgoo <https://github.com/oddgoo>!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jcastelli/meteor-parse-sdk/pull/3#issuecomment-101663033>
>> .
>>
>
>
>
> --
> *Cuauhtemoc Moreno*
> *Creative Coder and Game Designer*
>
>


-- 
*Cuauhtemoc Moreno*
*Creative Coder and Game Designer*

**Comment by jcastelli** [comment]
hahaha that's fantastic. It hasn't been too terribly long since I did the same!

**Pull request merged**
